kind: Development
apiVersion: apps/v1
metadata:
    name: madessen
spec:
    replicas: 2
    selector:       #tells the controller which pods to watch/belong to
      matchLabels:
        app: madessen
    template:
      metadata:
        labels:
          app: madessen
      spec:
        containers:
          - name: madessen
            image: madessen/pipeline-master
            imagePullPolicy: Always
            ports:
              - containerPort: 80